version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
          - IMAGE_NAME=${DOCKER_IMAGE_NAME}
          # I will inject above image name with my custom image name from jenkins pipeline

    image: ${DOCKER_IMAGE_NAME}
    networks:
      - mysql

networks:
  mysql:
    external: true